### ISSUE TITLE
javax.xml Maximum Element Depth limit is exceeded for genome-scale models

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#100]
```
javax.xml.stream.XMLStreamException: Maximum Element Depth limit (1000) Exceeded
	at com.ctc.wstx.sr.InputElementStack.push(InputElementStack.java:327)
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:3020)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2912)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1115)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromXMLEventReader(SBMLReader.java:568)
	at org.sbml.jsbml.xml.stax.SBMLReader.readXMLFromStream(SBMLReader.java:533)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromString(SBMLReader.java:834)
	at org.sbml.jsbml.xml.stax.SBMLReader.readSBMLFromString(SBMLReader.java:848)
	at org.sbml.jsbml.SBMLReader.readSBMLFromString(SBMLReader.java:267)
	at org.sbml.jsbml.SBMLReader.read(SBMLReader.java:143)
	at org.sbml.jsbml.JSBML.readSBMLFromString(JSBML.java:381)
```
The system property should be increased to deal with this.

**Comment by matthiaskoenig** [comment]
see 
http://dev.cs.uni-magdeburg.de/tutorials/Sun_Java_Tutorials/jaxp/limits/limits.html
http://dev.cs.uni-magdeburg.de/tutorials/Sun_Java_Tutorials/jaxp/limits/using.html
https://docs.oracle.com/javase/tutorial/jaxp/limits/limits.html

**Comment by matthiaskoenig** [comment]
probably an issue with JSBML
see https://groups.google.com/forum/#!topic/jsbml-development/cckEJPYNzQY
