### ISSUE TITLE
Cytoscape does not work with xerces

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#176]
There are provided jars which cause the conflicts with taverna:

```
framework/lib/endorsed/xercesImpl-2.11.0.jar
```

Similar issues seen here
https://github.com/sgtp/SemScape/issues/6
The proposed workaround crashes the JDK: Remove the framework/lib/endorsed/xercesImpl-2.11.0.jar file from the Cytoscape installation. 

Excluding xerces from taverna 

```
<exclusion>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
</exclusion>
```

results in 

```
java.lang.NoClassDefFoundError: org/apache/xerces/util/XMLChar
    at org.apache.jena.rdf.model.impl.Util.notNameChar(Util.java:119)
    at org.apache.jena.rdf.model.impl.Util.splitNamespaceXML(Util.java:77)
    at org.apache.jena.graph.Node_URI.getLocalName(Node_URI.java:80)
    at org.apache.jena.rdf.model.impl.ResourceImpl.getLocalName(ResourceImpl.java:152)
    at org.apache.jena.rdf.model.impl.PropertyImpl.checkLocalName(PropertyImpl.java:64)
    at org.apache.jena.rdf.model.impl.PropertyImpl.<init>(PropertyImpl.java:72)
    at org.apache.jena.rdf.model.ResourceFactory$Impl.createProperty(ResourceFactory.java:335)
    at org.apache.jena.rdf.model.ResourceFactory.createProperty(ResourceFactory.java:180)
    at org.apache.jena.vocabulary.RDF.property(RDF.java:51)
    at org.apache.jena.vocabulary.RDF.<clinit>(RDF.java:64)
    at org.apache.jena.system.InitJenaCore.init(InitJenaCore.java:57)
    at org.apache.jena.system.InitJenaCore.start(InitJenaCore.java:31)
    at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
    at java.util.ArrayList.forEach(ArrayList.java:1249)
    at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
```

Including xerces results in conflicting classes

```
java.lang.ClassCastException: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl cannot be cast to javax.xml.parsers.DocumentBuilderFactory
    at javax.xml.parsers.DocumentBuilderFactory.newInstance(Unknown Source)
```

Deleting the  framework/lib/endorsed/xercesImpl-2.11.0.jar crases the JDK with:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8ada37fa34, pid=10745, tid=0x00007f8968bbd700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6d9a34]  get_method_id(JNIEnv_*, _jclass*, char const*, char const*, bool, Thread*)+0x84
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/mkoenig/hs_err_pid10745.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by matthiaskoenig** [comment]
This is solved, and removed xerces dependencies. So no issue any more.
