### ISSUE TITLE
java.lang.NullPointerException with multiple HyperlinkListeners on multiple WebViews

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#183]
On startup the HyperlinkListener from LibFX

```
<dependency>
            <groupId>org.codefx.libfx</groupId>
            <artifactId>LibFX</artifactId>
            <version>0.3.0</version>
        </dependency>
```

result in a NullPointerException. Probably due to some concurrent or synchronization issues. This does not affect the functionality, but should still be fixed.

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at org.codefx.libfx.control.webview.DefaultWebViewHyperlinkListenerHandle.onEachLinkForEachManagedEventType(DefaultWebViewHyperlinkListenerHandle.java:200)
    at org.codefx.libfx.control.webview.DefaultWebViewHyperlinkListenerHandle.attachListenerInApplicationThread(DefaultWebViewHyperlinkListenerHandle.java:147)
    at org.codefx.libfx.control.webview.DefaultWebViewHyperlinkListenerHandle.lambda$attachInApplicationThreadEachTimeLoadSucceeds$38(DefaultWebViewHyperlinkListenerHandle.java:133)
    at org.codefx.libfx.concurrent.when.ExecuteAlwaysWhen.tryExecuteAction(ExecuteAlwaysWhen.java:168)
    at org.codefx.libfx.concurrent.when.ExecuteAlwaysWhen.lambda$new$17(ExecuteAlwaysWhen.java:121)
    at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
    at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
    at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
    at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
    at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
    at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
    at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
    at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
    at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
    at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
    at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2416)
    at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2260)
    at com.sun.webkit.network.URLLoader.twkDidFinishLoading(Native Method)
    at com.sun.webkit.network.URLLoader.notifyDidFinishLoading(URLLoader.java:838)
    at com.sun.webkit.network.URLLoader.lambda$didFinishLoading$98(URLLoader.java:829)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by matthiaskoenig** [comment]
Cannot reproduce
