### ISSUE TITLE
Some errors in styles on startup

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#249]
Errors are accessible after startup:
![screenshot from 2017-11-12 01-13-24](https://user-images.githubusercontent.com/900538/32694697-e7ae43b6-c746-11e7-91f4-ba0a6377c525.png)

**Comment by matthiaskoenig** [comment]
The RGB values are fixed. Loads without problems in Cy3.5, still some warning in Cy3.6.

**Comment by matthiaskoenig** [comment]
Narrowed it down to 
```
java.lang.NumberFormatException: For input string: "species"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.cytoscape.io.internal.util.vizmap.VisualStyleSerializer.createVisualProperties(VisualStyleSerializer.java:433)
	at org.cytoscape.io.internal.util.vizmap.VisualStyleSerializer.createVisualStyles(VisualStyleSerializer.java:150)
	at org.cytoscape.io.internal.read.vizmap.VizmapXMLReader.run(VizmapXMLReader.java:57)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
	at org.cytoscape.task.internal.vizmap.LoadVizmapFileTaskFactoryImpl.loadStyles(LoadVizmapFileTaskFactoryImpl.java:82)
	at org.cytoscape.task.internal.vizmap.LoadVizmapFileTaskFactoryImpl.loadStyles(LoadVizmapFileTaskFactoryImpl.java:101)
	at org.cy3sbml.styles.StyleManager.loadStyles(StyleManager.java:57)
	at org.cy3sbml.CyActivator.start(CyActivator.java:193)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2064)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:942)
	at org.cytoscape.app.internal.manager.BundleApp.start(BundleApp.java:82)
	at org.cytoscape.app.internal.manager.AppManager.startApps(AppManager.java:406)
	at org.cytoscape.app.internal.manager.AppManager.initializeApps(AppManager.java:376)
	at org.cytoscape.app.internal.manager.AppManager.lambda$attemptInitialization$0(AppManager.java:237)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  (org.cy3sbml.styles.StyleManager) - Load visual style: cy3sbml-dark
java.lang.NumberFormatException: For input string: "species"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.cytoscape.io.internal.util.vizmap.VisualStyleSerializer.createVisualProperties(VisualStyleSerializer.java:433)
	at org.cytoscape.io.internal.util.vizmap.VisualStyleSerializer.createVisualStyles(VisualStyleSerializer.java:150)
	at org.cytoscape.io.internal.read.vizmap.VizmapXMLReader.run(VizmapXMLReader.java:57)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92)
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108)
	at org.cytoscape.task.internal.vizmap.LoadVizmapFileTaskFactoryImpl.loadStyles(LoadVizmapFileTaskFactoryImpl.java:82)
	at org.cytoscape.task.internal.vizmap.LoadVizmapFileTaskFactoryImpl.loadStyles(LoadVizmapFileTaskFactoryImpl.java:101)
	at org.cy3sbml.styles.StyleManager.loadStyles(StyleManager.java:57)
	at org.cy3sbml.CyActivator.start(CyActivator.java:193)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:645)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2146)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2064)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:955)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:942)
	at org.cytoscape.app.internal.manager.BundleApp.start(BundleApp.java:82)
	at org.cytoscape.app.internal.manager.AppManager.startApps(AppManager.java:406)
	at org.cytoscape.app.internal.manager.AppManager.initializeApps(AppManager.java:376)
	at org.cytoscape.app.internal.manager.AppManager.lambda$attemptInitialization$0(AppManager.java:237)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
