### ISSUE TITLE
java.lang.NullPointerException when getting derivedUnits of some reactions

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#256]
This is an JSBML issue,  see discussion here
https://groups.google.com/forum/#!topic/jsbml-development/AlzHCwHdoCA
```
Exception in thread "main" java.lang.NullPointerException
    at org.sbml.jsbml.util.converters.ExpandFunctionDefinitionConverter$3.accepts(ExpandFunctionDefinitionConverter.java:229)
    at org.sbml.jsbml.AbstractTreeNode.filter(AbstractTreeNode.java:361)
    at org.sbml.jsbml.AbstractTreeNode.filter(AbstractTreeNode.java:352)
    at org.sbml.jsbml.AbstractTreeNode.filter(AbstractTreeNode.java:344)
    at org.sbml.jsbml.util.converters.ExpandFunctionDefinitionConverter.replaceAll(ExpandFunctionDefinitionConverter.java:220)
    at org.sbml.jsbml.util.converters.ExpandFunctionDefinitionConverter.access$000(ExpandFunctionDefinitionConverter.java:59)
    at org.sbml.jsbml.util.converters.ExpandFunctionDefinitionConverter$2.accepts(ExpandFunctionDefinitionConverter.java:172)
    at org.sbml.jsbml.AbstractTreeNode.filter(AbstractTreeNode.java:361)
    at org.sbml.jsbml.AbstractTreeNode.filter(AbstractTreeNode.java:374)
    at org.sbml.jsbml.util.converters.ExpandFunctionDefinitionConverter.expandFunctionDefinition(ExpandFunctionDefinitionConverter.java:142)
    at org.sbml.jsbml.AbstractMathContainer.getDerivedUnitDefinition(AbstractMathContainer.java:185)
    at org.sbml.jsbml.AbstractMathContainer.getDerivedUnits(AbstractMathContainer.java:229)
    at org.sbml.jsbml.Reaction.getDerivedUnits(Reaction.java:581)
    at org.cy3sbml.oven.UnitJSBMLTest.main(UnitJSBMLTest.java:20)
```

**Comment by matthiaskoenig** [comment]
Fixed by Nico.
