### ISSUE TITLE
Problems with missing strict tags on fbc

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#269]
```
org.cy3sbml.SBMLReaderError: cy3sbml reader failed to build a SBML model. Please validate the file in the online SBML validator at 'http://www.sbml.org/validator/'and report the issue at 'https://github.com/matthiaskoenig/cy3sbml/issues'java.lang.NullPointerException
	at org.cy3sbml.SBMLReaderTask.run(SBMLReaderTask.java:365)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:342)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:355)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by matthiaskoenig** [comment]
Problem of invalid SBML files with missing tags.
