### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null on SBML loading

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#289]
Some events are not handled correctly, resulting in many of the following errors on SBML loading:

```
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.cytoscape.event.internal.CyListenerAdapter.fireEvent(CyListenerAdapter.java:120) ~[?:?]
	at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:169) ~[?:?]
	at org.cytoscape.event.internal.CyEventHelperImpl.flushPayloadEvents(CyEventHelperImpl.java:151) ~[?:?]
	at org.cytoscape.ding.impl.DGraphView.fitContent(DGraphView.java:967) ~[?:?]
	at org.cytoscape.ding.impl.DGraphView.fitContent(DGraphView.java:1019) ~[?:?]
	at org.cytoscape.view.layout.AbstractLayoutTask.run(AbstractLayoutTask.java:177) ~[?:?]
	at org.cy3sbml.SBMLReaderTask.buildCyNetworkView(SBMLReaderTask.java:203) ~[?:?]
	at org.cytoscape.task.internal.export.network.GenerateNetworkViewsTask.createNetworkView(GenerateNetworkViewsTask.java:162) ~[?:?]
	at org.cytoscape.task.internal.export.network.GenerateNetworkViewsTask.run(GenerateNetworkViewsTask.java:101) ~[?:?]
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:92) ~[?:?]
	at org.cytoscape.work.internal.sync.SyncTaskManager.execute(SyncTaskManager.java:108) ~[?:?]
	at org.cy3sbml.util.GUIUtil.loadExampleFromResource(GUIUtil.java:55) ~[?:?]
	at org.cy3sbml.gui.BrowserHyperlinkListener.processURLEvent(BrowserHyperlinkListener.java:165) ~[?:?]
	at org.cy3sbml.gui.BrowserHyperlinkListener.hyperlinkUpdate(BrowserHyperlinkListener.java:91) ~[?:?]
	at org.codefx.libfx.control.webview.DefaultWebViewHyperlinkListenerHandle.callHyperlinkListenerWithEvent(DefaultWebViewHyperlinkListenerHandle.java:263) ~[?:?]
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129) ~[?:?]
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method) ~[?:?]
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807) ~[?:?]
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045) ~[?:?]
	at javafx.scene.web.WebView.lambda$registerEventHandlers$8(WebView.java:1168) ~[?:?]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[?:?]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) ~[?:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) ~[?:?]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) ~[?:?]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[?:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) ~[?:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[?:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[?:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[?:?]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) ~[?:?]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) ~[?:?]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) ~[?:?]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) ~[?:?]
	at javafx.event.Event.fireEvent(Event.java:198) ~[?:?]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[?:?]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[?:?]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[?:?]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[?:?]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$302(EmbeddedScene.java:256) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$mouseEvent$303(EmbeddedScene.java:244) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$397(PlatformImpl.java:295) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$398(PlatformImpl.java:294) ~[?:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[?:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[?:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.NullPointerException
	at org.cy3sbml.gui.WebViewPanel.handleEvent(WebViewPanel.java:264) ~[?:?]
	... 51 more
```

**Comment by kyxhik** [comment]
For some reason, CyNetwork network = adapter.cyApplicationManager.getCurrentNetwork() (under RowSetEvent) returns null. I think it is because it is trying to fetch the network before it is fully loaded. I added a (if network!=null) loop around it to make the error disappear.

Any other suggestions? @matthiaskoenig @draeger

**Comment by matthiaskoenig** [comment]
Has been fixed as part of gsoc2025.
