### ISSUE TITLE
Issue with reading SBML Test suite

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#313]
Problems loading test model
```
[01190.zip](https://github.com/matthiaskoenig/cy3sbml/files/4717579/01190.zip)

java.lang.NullPointerException: null
	at java.base/java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1470)
	at java.base/java.text.DateFormat.parse(DateFormat.java:393)
	at org.cy3sbml.miriam.RegistryUtil.getLatestDataVersionDate(RegistryUtil.java:128)
	at org.cy3sbml.miriam.RegistryUtil.updateMiriamXMLWithNewer(RegistryUtil.java:81)
	at org.cy3sbml.CyActivator$1.run(CyActivator.java:305)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.cy3sbml.CyActivator.start(CyActivator.java:309)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.cytoscape.app.internal.manager.BundleApp.start(BundleApp.java:82)
	at org.cytoscape.app.internal.manager.AppManager.startApps(AppManager.java:404)
	at org.cytoscape.app.internal.manager.AppManager.initializeApps(AppManager.java:374)
	at org.cytoscape.app.internal.manager.AppManager.lambda$attemptInitialization$0(AppManager.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NullPointerException
	at java.base/java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1470)
	at java.base/java.text.DateFormat.parse(DateFormat.java:393)
	at org.cy3sbml.miriam.RegistryUtil.getLatestDataVersionDate(RegistryUtil.java:128)
	at org.cy3sbml.miriam.RegistryUtil.updateMiriamXMLWithNewer(RegistryUtil.java:81)
	at org.cy3sbml.CyActivator$1.run(CyActivator.java:305)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.cy3sbml.CyActivator.start(CyActivator.java:309)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2240)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2146)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
	at org.cytoscape.app.internal.manager.BundleApp.start(BundleApp.java:82)
	at org.cytoscape.app.internal.manager.AppManager.startApps(AppManager.java:404)
	at org.cytoscape.app.internal.manager.AppManager.initializeApps(AppManager.java:374)
	at org.cytoscape.app.internal.manager.AppManager.lambda$attemptInitialization$0(AppManager.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.NumberFormatException: For input string: "1190"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.valueOf(Integer.java:957) ~[?:?]
	at java.lang.Integer.decode(Integer.java:1436) ~[?:?]
	at org.cytoscape.session.internal.CyNetworkNamingImpl.getSuggestedNetworkTitle(CyNetworkNamingImpl.java:96) ~[?:?]
	at org.cytoscape.task.internal.export.network.GenerateNetworkViewsTask.run(GenerateNetworkViewsTask.java:95) ~[?:?]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337) ~[93:org.cytoscape.work-swing-impl:3.8.0]
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352) [93:org.cytoscape.work-swing-impl:3.8.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
java.lang.NumberFormatException: For input string: "1190"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:957)
	at java.base/java.lang.Integer.decode(Integer.java:1436)
	at org.cytoscape.session.internal.CyNetworkNamingImpl.getSuggestedNetworkTitle(CyNetworkNamingImpl.java:96)
	at org.cytoscape.task.internal.export.network.GenerateNetworkViewsTask.run(GenerateNetworkViewsTask.java:95)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
	at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:352)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by matthiaskoenig** [comment]
Solved as part of #310
