### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: width of node has degenerated to zero after rounding

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/cy3sbml#85]
When proceesing cofactor nodes (adding/removing nodes from the subnetworks) there is sometimes a degraded node view (node with visualStyle not applied).
See also 
https://gist.github.com/momeara/4833e93631f5908ec31d
which has the same issue.

Not really clear what the reason is, but probably also some Swing related thing (view updated before the style information is available ?)
Seems to be a Cytoscape issue so reported here for now
https://code.cytoscape.org/redmine/issues/3502

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: width of node has degenerated to zero after rounding
	at org.cytoscape.ding.impl.DNodeView.setOffset(DNodeView.java:470)
	at org.cytoscape.ding.impl.InnerCanvas$MouseDraggedDelegator.singleLeftClick(InnerCanvas.java:1524)
	at org.cytoscape.ding.impl.InnerCanvas$MouseDraggedDelegator.delegateMouseEvent(InnerCanvas.java:1460)
	at org.cytoscape.ding.impl.InnerCanvas.mouseDragged(InnerCanvas.java:337)
	at org.cytoscape.ding.impl.cyannotator.listeners.CanvasMouseMotionListener.mouseDragged(CanvasMouseMotionListener.java:58)
	at java.awt.AWTEventMulticaster.mouseDragged(AWTEventMulticaster.java:319)
	at java.awt.Component.processMouseMotionEvent(Component.java:6583)
	at javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3342)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4542)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by matthiaskoenig** [comment]
Fixed in trunk for 3.4 Cytoscape release.
Works with latest nightly build.
http://code.cytoscape.org/jenkins/job/cytoscape-3-gui-distribution/lastSuccessfulBuild/org.cytoscape.distribution$cytoscape/
